meta_product_name: "Gringeat"
meta_title: "Gringeat - The app that helps expats understand products"
meta_description: "Gringeat is based on the simple idea of enabling expatriates to understand their new environment, the brands and products of the country in which they live. You scan a product and you get all the information about it. Simple, effective, Gringeat allows its users to take back control and understand their purchases."
meta_image: "cover.png" # should exist in `app/assets/images/`
